# Generated by Django 4.1.3 on 2022-11-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotels_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='place',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
