# Generated by Django 4.1.3 on 2022-11-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotels_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='airplane_prices',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
