# Generated by Django 4.1.3 on 2022-11-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotelimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotels',
            name='images',
            field=models.ManyToManyField(related_name='images', to='hotels.hotelimage'),
        ),
    ]
