# Generated by Django 4.1.3 on 2022-11-17 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_remove_hotelimage_hotel_hotels_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='images',
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotels'),
            preserve_default=False,
        ),
    ]
