# Generated by Django 4.1.3 on 2022-11-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_hotels_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='rooms',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
