# Generated by Django 4.1.3 on 2022-11-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address',
            field=models.CharField(default=1, max_length=170),
            preserve_default=False,
        ),
    ]
